# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed

# For beginners, we downscale velocity and acceleration limits.
# You can always specify higher scaling factors (<= 1.0) in your motion requests.  # Increase the values below to 1.0 to always move at maximum speed.
default_velocity_scaling_factor: 1.0
default_acceleration_scaling_factor: 1.0

# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  rover_arm_base_joint:
    has_velocity_limits: true
    max_velocity: 1.15 #by math 5.5
    has_acceleration_limits: true
    max_acceleration: 2.75 #math 5.5
  rover_arm_shoulder_joint:
    has_velocity_limits: true
    max_velocity: 0.72 #math 3.5
    has_acceleration_limits: true
    max_acceleration: 1.4 #math 3.5
  rover_arm_elbow_pitch_joint:
    has_velocity_limits: true
    max_velocity: 1.17 #math 5.6
    has_acceleration_limits: true
    max_acceleration: 2.8 #math 5.6
  rover_arm_elbow_roll_joint:
    has_velocity_limits: true
    max_velocity: 3.88 #math 18.5
    has_acceleration_limits: true
    max_acceleration: 9.25 #math 18.5
  rover_arm_wrist_pitch_joint:
    has_velocity_limits: true
    max_velocity: 1.23 # math 5.9
    has_acceleration_limits: true
    max_acceleration: 5.95 # math 5.9
  rover_arm_wrist_roll_joint:
    has_velocity_limits: true
    max_velocity: 4.61 #math 22.0
    has_acceleration_limits: true
    max_acceleration: 11.0 #math 22.0