# RTABMap ROS2 Parameters Configuration

rtabmap:
  ros__parameters:
    # use_sim_time: true
    
    # Frames
    frame_id: "rover_base_origin"        # base link frame
    odom_frame_id: "odom"                # set this to get odom from the tf instead of a topic sub
    map_frame_id: "map"                  # set tf head to "world" instead of "map" to avoid tf conflicts
    
    # Rtab params
    subscribe_depth: true
    subscribe_rgb: true
    subscribe_odom_info: false
    approx_sync: true                    # Odom is from external source, so best to approx sync?
    publish_tf: false                    # KRJ TODO: Setting this to false for now, so that it does not interfere with gps map frame.
    
    # Internal parameters (must be strings)
    # /Grid
    # Configure generation of obstacle map
    Grid/3D: "false"                     # We do not want octomap. Saves memory and time. Allows raytracing?
    Grid/CellSize: "0.05"
    # Grid/RangeMin: "0.0"                 # 0 default
    # Grid/RangeMax: "5"                   # 5 default
    Grid/MaxGroundAngle: "60"
    Grid/RayTracing: "true"              # Fill empty space
    # Grid/FromDepth: "true"             # KRJ TODO: IDK what this was for
    # Grid/MaxGroundHeight: "0.1"
    # Grid/MapFrameProjection: "true"

    # optimizer
    # Optimizer/Strategy: "1" # 0=TORO, 1=g2o, 2=GTSAM and 3=Ceres
    # Optimizer/Iteration: "20"
    # Optimizer/Epsilon: "0.000001"    # Stop optimizing when the error improvement is less than this value.  
    # Optimizer/Robust: "true"    # Required to remove bad loop closured from map in post. Robust graph optimization using Vertigo (only work for g2o and GTSAM optimization strategies)
    # RGBD/OptimizeMaxError: "2"  # 3 by default

    RGBD/NeighborLinkRefining: 'false'
    RGBD/ProximityBySpace':     'false'  # Referred paper did only global loop closure detection
    RGBD/OptimizeFromGraphEnd': 'true'   # more compute, but if set to false, could have more jumpy map
    Reg/Strategy':              '1'
    Icp/Iterations':            '30'
    Icp/VoxelSize':             '0'
    Vis/MinInliers':            '12'
    Vis/MaxDepth':              '0'
    RGBD/AngularUpdate':        '0.05'  # KRJ changed: .01 - .05 to reduce compute
    RGBD/LinearUpdate':         '0.05'  # KRJ changed: .01 - .05 to reduce compute
    Rtabmap/TimeThr':           '700'
    Mem/RehearsalSimilarity':   '0.30'   
    Kp/TfIdfLikelihoodUsed':    'false'
    Bayes/FullPredictionUpdate': 'false' # KRJ changed: save compute
    Kp/DetectorStrategy':       '1'      
    Vis/FeatureType':           '1'      
    Kp/MaxFeatures':            '400'
    Reg/Force3DoF':             'false'   # KRJ changed: we will be moving on 3D terrain
    RGBD/OptimizeMaxError':     '3'       # KRJ changed: from 10 to default 3, only accept good closures
    Optimizer/Strategy':        '2'       # This is default
    Optimizer/Iterations':      '30'      # KRJ changed: reduced from 100 to save processing
    Kp/IncrementalFlann':       'true'    # KRJ changed: save processing
    Icp/MaxTranslation':        '0.5'
    
    # Noise filtering
    # KRJ TODO: This could break it if it filters out too many
    Grid/NoiseFilteringRadius: "0.1"     # Must have so many neighbors within radius to be considered. Done after segmentation
    Grid/NoiseFilteringMinNeighbors: "2"
    GridGlobal/Eroded: "true"            # Take off the outer edge of obstacles (grid square only included if all of its neighbors are obstacles)
    
    # Other stuff
    # Grid/MinClusterSize: "10"            # 10 default. Minimum cluster size to project the points. KRJ TODO: How is this different from noise filtering min neighbors. I don't think I understand what this does, so I'm not gonna mess with it. Its part of segmenting ground from objects by normals
    # GridGlobal/FootprintRadius: "0.2"    # Footprint radius (m) used to clear all obstacles under the graph.
    
    # /Optimizer
    # Optimizer/PriorsIgnored: "false"   # Fuse GPS as a prior
    
    # Note from the docs: "Currently only g2o and gtsam optimization supports this."
    # It is ambiguous whether this is referring to supporting priors or supporting ignoring priors
    # By default the optimization method is neither of these, should be TORO (double check this)
    
    # /Rtabmap
    # Some general params for loop closure thresholds
    # Rtabmap/LoopGPS: "true"
    
    # Internal parameters (must be strings)
    # /Reg and /Vis
    # Configure point cloud registration (first step in sticking frames together)
    
    # /RGBD
    # Configure loop closure and graph optimization for RGBD
    
    # Reduce computation?
    # Grid/DepthDecimation: "8"          # 4 by default
    # Grid/NormalK: "10"                 # 20 by default